<?php
// vim: set tabstop=4 
// +===========================================================================+
// | Facebook Connect Magento Helper                                           |
// +===========================================================================+
// | License: Proprietary                                                      |
// +===========================================================================+
// | Copyright (c) 2009 Mark Kimsal                                            |
// | All rights reserved.                                                      |
// |                                                                           |
// | Redistribution and use in source and binary forms, with or without        |
// | modification, are not permitted without express written consent.          |
// |                                                                           |
// |                                                                           |
// | THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       |
// | "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         |
// | LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR     |
// | A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER|
// | OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  |
// | EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,       |
// | PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR        |
// | PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    |
// | LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      |
// | NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        |
// | SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              |
// +===========================================================================+

//skip specialized block creation for a lighter-weight module.

$hasFbAcct = Mage::helper('fbconnect/account')->userHasFbAccount();
?>
<div class="page-head">
    <h3><?php echo $this->__('Facebook Settings') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php
//only show this form if the user has not already logged in via facebook
if (!$hasFbAcct):
?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
<fieldset class="group-select">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Account Information') ?></h4>
    <ul>
        <li>
            <?php /* echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml()*/ ?>
		</li>
        <li>
            <div class="input-box">
            <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
            <input type="text" name="email" id="email" value="<?php /* echo $this->htmlEscape($this->getCustomer()->getEmail()) */ ?>" title="<?php echo $this->__('Email Address') ?>" class="required-entry validate-email input-text" />
            </div>
        </li>
    </ul>
</fieldset>
<p><input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php /* if($this->getCustomer()->getChangePassword()==1): echo 'checked="checked"'; endif;*/ ?> /> <label for="change_password"><?php echo $this->__('Change Password') ?></label>
</p>
<fieldset class="group-select" style="display:none">
    <h4 class="legend"><?php echo $this->__('Change Password') ?></h4>
    <ul>
        <li>
            <div class="input-box">
                <label for="current_password"><?php echo $this->__('Current Password') ?></label><br/>
                <input type="password" class="input-text" name="current_password" id="current_password" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="password"><?php echo $this->__('New Password') ?></label><br/>
                <input type="password" class="validate-password input-text" name="password" id="password" />
            </div>
            <div class="input-box">
                <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label><br/>
                <input type="password" class="validate-cpassword input-text" name="confirmation" id="confirmation" />
            </div>
        </li>
    </ul>
</fieldset>
<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="submit" class="form-button"><span><?php echo $this->__('Save') ?></span></button>
</div>
</form>
<?php
endif; //!$hasFbAcct
?>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
