<?php
// vim: set tabstop=4 
// +===========================================================================+
// | Facebook Connect Magento Helper                                           |
// +===========================================================================+
// | License: Proprietary                                                      |
// +===========================================================================+
// | Copyright (c) 2009 Mark Kimsal                                            |
// | All rights reserved.                                                      |
// |                                                                           |
// | Redistribution and use in source and binary forms, with or without        |
// | modification, are not permitted without express written consent.          |
// |                                                                           |
// |                                                                           |
// | THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS       |
// | "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT         |
// | LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR     |
// | A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER|
// | OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  |
// | EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,       |
// | PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR        |
// | PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF    |
// | LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING      |
// | NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS        |
// | SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.              |
// +===========================================================================+

//skip specialized block creation for a lighter-weight module.

$hasFbAcct = Mage::helper('fbconnect/account')->userHasFbAccount();
$alreadyClaimed = Mage::helper('fbconnect/account')->userHasClaimedAccount();
?>
<div class="page-head">
    <h3><?php echo $this->__('Facebook Settings') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if (!$hasFbAcct):
//only show this form if the user has not already logged in via facebook
?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
<fieldset class="group-select">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Connect to Facebook') ?></h4>
    <ul>
        <li>
			<p><?php echo Mage::helper('fbconnect')->__('Click the button below if you would like to connect your Facebook account with this one.');?><br/><a href="<?php echo $this->helper('fbconnect')->getLoginUrl();?>" ><img id="fb_login_image" src="<?php echo Mage::helper('fbconnect')->getFbButtonSrc();?>" alt="Connect"/> </a></p>
            <div class="input-box">
            </div>
        </li>
    </ul>
</fieldset>

<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="submit" class="form-button"><span><?php echo $this->__('Save') ?></span></button>
</div>
</form>
<?php endif; //!$hasFbAcct ?>

<?php if ($hasFbAcct && !$alreadyClaimed):
//if the user has a facebook account, and they haven't declined to claim an 
// existing account, show the form
?>


<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
<div class="login-box">
    <div class="col-2 registered-users">
        <div class="content">
            <h4><?php echo $this->__('Connect to an existing Account') ?></h4>
            <p><?php echo $this->__('Enter your current username and password to connect your Facebook account with a previously registered account.') ?></p>
            <ul class="form-list">
                    <li>
                        <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
                        <input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" title="<?php echo $this->__('Email Address') ?>" id="email" type="text" class="input-text required-entry" style="width:250px;" />
                    </li>
                    <li>
                        <label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
                        <input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" style="width:250px;" />
                    </li>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        </div>
		<div class="button-set">
			<button class="form-button" type="submit" name="send" id="send2"><span><?php echo $this->__('Connect') ?></span></button>
		</div>
    </div>
</div>
</form>





<?php endif; //$hasFbAcct && !$alreadyClaimed ?>
