
<?php if (Mage::getStoreConfig('metrof_fbc/fbconnect/use_fbconnect')) { ?>
<script src="<?php echo $this->helper('fbconnect')->getFeatureLoaderSrc();?>" type="text/javascript"></script>
<script type="text/javascript">
	FB_RequireFeatures(["Connect"], function(){
	FB.init("<?php echo $this->helper('fbconnect')->getApiKey();?>", "<?php echo $this->helper('fbconnect')->getXdReceiverUrl();?>");
	//  FB.XdComm.Server.init(<site relative url to xd_receiver.htm>);
	//  FB.CanvasClient.startTimerToSizeToContent();
	});
</script>

<?php } ?>
<!--
    <div class="collateral-box">
		<div class="head"><h4>Comments</h4></div>
<fb:comments> </fb:comments>
	</div>
-->
